# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_on_date', models.DateTimeField(auto_now_add=True)),
                ('modified_on_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HtmlTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255, unique=True)),
                ('tag_text', models.TextField()),
                ('created_on_date', models.DateTimeField(auto_now_add=True)),
                ('modified_on_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255, unique=True)),
                ('script_text', models.TextField()),
                ('created_on_date', models.DateTimeField(auto_now_add=True)),
                ('modified_on_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityIdModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[(b'-1', b'None'), (b'00', b'User'), (b'01', b'Group'), (b'02', b'Role'), (b'03', b'Capability')], default=b'-1', max_length=2)),
                ('value', models.CharField(max_length=255)),
                ('created_on_date', models.DateTimeField(auto_now_add=True)),
                ('modified_on_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255, unique=True)),
                ('style_text', models.TextField()),
                ('created_on_date', models.DateTimeField(auto_now_add=True)),
                ('modified_on_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('security_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.SecurityIdModel')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
            ],
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='StyleModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('style_type', models.CharField(max_length=255)),
                ('style_path', models.FilePathField(match='([a-z][A-Z]).*\\.html$', path=b'C:\\Users\\Admin\\Documents\\Projects\\Python\\Django\\IOTStudio')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
            },
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('template_type', models.CharField(max_length=255)),
                ('template_path', models.FilePathField(match='([a-z][A-Z]).*\\.html$', path=b'C:\\Users\\Admin\\Documents\\Projects\\Python\\Django\\IOTStudio')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='UIElementModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('element_type', models.CharField(max_length=255)),
            ],
            bases=('gui.basemodel',),
        ),
        migrations.AddField(
            model_name='scripttag',
            name='security_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.SecurityIdModel'),
        ),
        migrations.AddField(
            model_name='htmltag',
            name='security_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.SecurityIdModel'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='security_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.SecurityIdModel'),
        ),
        migrations.CreateModel(
            name='ControlModel',
            fields=[
                ('uielementmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.UIElementModel')),
                ('control_type', models.CharField(max_length=255)),
            ],
            bases=('gui.uielementmodel',),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='selected_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.TemplateModel'),
        ),
        migrations.CreateModel(
            name='ContentControlModel',
            fields=[
                ('controlmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.ControlModel')),
            ],
            options={
                'verbose_name': 'ContentControl',
                'verbose_name_plural': 'ContentControls',
            },
            bases=('gui.controlmodel',),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='template_applied_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.ControlModel'),
        ),
        migrations.AddField(
            model_name='stylemodel',
            name='style_applied_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.ControlModel'),
        ),
        migrations.AddField(
            model_name='controlmodel',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.ControlModel'),
        ),
        migrations.CreateModel(
            name='ItemsControlModel',
            fields=[
                ('contentcontrolmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.ContentControlModel')),
            ],
            options={
                'verbose_name': 'ItemsControl',
                'verbose_name_plural': 'ItemsControls',
            },
            bases=('gui.contentcontrolmodel',),
        ),
        migrations.AddField(
            model_name='contentcontrolmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcontrolmodel',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.ContentControlModel'),
        ),
        migrations.AddField(
            model_name='contentcontrolmodel',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.StyleModel'),
        ),
        migrations.AddField(
            model_name='contentcontrolmodel',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.TemplateModel'),
        ),
        migrations.AddField(
            model_name='itemscontrolmodel',
            name='items',
            field=models.ManyToManyField(related_name='_itemscontrolmodel_items_+', to='gui.ContentControlModel'),
        ),
    ]
