# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_on_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('author', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
            ],
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
            ],
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='StyleModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('style_type', models.CharField(max_length=255)),
                ('style_path', models.CharField(max_length=255)),
            ],
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('template_type', models.CharField(max_length=255)),
                ('template_path', models.CharField(max_length=255)),
            ],
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='UIElementModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('element_type', models.CharField(max_length=255)),
            ],
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='ControlModel',
            fields=[
                ('uielementmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.UIElementModel')),
                ('control_type', models.CharField(max_length=255)),
            ],
            bases=('gui.uielementmodel',),
        ),
        migrations.CreateModel(
            name='ContentControlModel',
            fields=[
                ('controlmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.ControlModel')),
            ],
            bases=('gui.controlmodel',),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='template_applied_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.ControlModel'),
        ),
        migrations.AddField(
            model_name='stylemodel',
            name='style_applied_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.ControlModel'),
        ),
        migrations.AddField(
            model_name='controlmodel',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.ControlModel'),
        ),
        migrations.CreateModel(
            name='ItemsControlModel',
            fields=[
                ('contentcontrolmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.ContentControlModel')),
            ],
            bases=('gui.contentcontrolmodel',),
        ),
        migrations.AddField(
            model_name='contentcontrolmodel',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.ContentControlModel'),
        ),
        migrations.AddField(
            model_name='contentcontrolmodel',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.StyleModel'),
        ),
        migrations.AddField(
            model_name='contentcontrolmodel',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.TemplateModel'),
        ),
        migrations.AddField(
            model_name='itemscontrolmodel',
            name='items',
            field=models.ManyToManyField(related_name='_itemscontrolmodel_items_+', to='gui.ContentControlModel'),
        ),
    ]
