# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='security_id',
            field=models.IntegerField(default=0),
        ),
    ]
