# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_basemodel_security_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='selected_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.TemplateModel'),
        ),
    ]
