# Generated by Django 2.0.1 on 2018-01-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_applicationmodel_selected_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='created_on_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
