# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_auto_20180114_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlTags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_text', models.CharField(max_length=5000)),
                ('created_on_date', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
                ('security_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScriptTags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
                ('script_text', models.CharField(max_length=5000)),
                ('created_on_date', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
                ('security_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StyleTags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
                ('style_text', models.CharField(max_length=5000)),
                ('created_on_date', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
                ('security_id', models.IntegerField()),
            ],
        ),
    ]
