# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 13:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_auto_20180115_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmodel',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='contentcontrolmodel',
            options={'verbose_name': 'ContentControl', 'verbose_name_plural': 'ContentControls'},
        ),
        migrations.AlterModelOptions(
            name='itemscontrolmodel',
            options={'verbose_name': 'ItemsControl', 'verbose_name_plural': 'ItemsControls'},
        ),
        migrations.AlterModelOptions(
            name='stylemodel',
            options={'verbose_name': 'Style', 'verbose_name_plural': 'Styles'},
        ),
        migrations.AlterModelOptions(
            name='templatemodel',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterField(
            model_name='htmltag',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='htmltag',
            name='created_on_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created on date'),
        ),
        migrations.AlterField(
            model_name='htmltag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='htmltag',
            name='security_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scripttag',
            name='created_on_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created on date'),
        ),
        migrations.AlterField(
            model_name='scripttag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scripttag',
            name='security_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='styletag',
            name='created_on_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created on date'),
        ),
        migrations.AlterField(
            model_name='styletag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='styletag',
            name='security_id',
            field=models.IntegerField(default=0),
        ),
    ]
