# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gui', '0006_auto_20180116_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageIconTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255, unique=True)),
                ('icon_type', models.CharField(choices=[('-1', 'None'), ('00', 'File'), ('01', 'Inline')], default='00', max_length=2)),
                ('icon_file', models.FilePathField(blank=True, null=True, path='C:\\Users\\Admin\\Documents\\Projects\\Python\\Django\\IOTStudio\\staticfiles/img', recursive=True)),
                ('icon_text', models.TextField(blank=True, null=True)),
                ('created_on_date', models.DateTimeField(auto_now_add=True)),
                ('modified_on_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('security_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.SecurityIdModel')),
            ],
        ),
    ]
