# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_auto_20180116_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripttag',
            name='script_url',
            field=models.URLField(blank=True, help_text='Url to CDN location', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scripttag',
            name='script_type',
            field=models.CharField(choices=[('-1', 'None'), ('00', 'File'), ('01', 'Inline'), ('02', 'Url')], default='02', max_length=2),
        ),
    ]
