# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_auto_20180116_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodel',
            name='header_script_tags',
            field=models.ManyToManyField(related_name='_templatemodel_header_script_tags_+', to='gui.ScriptTag'),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='header_style_tags',
            field=models.ManyToManyField(related_name='_templatemodel_header_style_tags_+', to='gui.StyleTag'),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='meta_tags',
            field=models.ManyToManyField(related_name='_templatemodel_meta_tags_+', to='gui.HtmlTag'),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='page_icon_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.IconTag'),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='title_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.HtmlTag'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='template_type',
            field=models.CharField(choices=[('-1', 'None'), ('00', 'File'), ('01', 'Runtime')], default='00', max_length=2),
        ),
    ]
