# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0011_auto_20180117_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='header_script_tags',
            field=models.ManyToManyField(blank=True, related_name='_templatemodel_header_script_tags_+', to='gui.ScriptTag'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='header_style_tags',
            field=models.ManyToManyField(blank=True, related_name='_templatemodel_header_style_tags_+', to='gui.StyleTag'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='meta_tags',
            field=models.ManyToManyField(blank=True, related_name='_templatemodel_meta_tags_+', to='gui.HtmlTag'),
        ),
    ]
