# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gui', '0013_auto_20180117_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlStyleModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('style_type', models.CharField(choices=[('-1', 'None'), ('00', 'File'), ('01', 'Inline')], default='01', max_length=2)),
                ('style_path', models.FilePathField(blank=True, null=True, path='C:\\Users\\Admin\\Documents\\Projects\\Python\\Django\\IOTStudio\\staticfiles/css', recursive=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('style_applied_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.ControlModel')),
            ],
            options={
                'verbose_name': 'ControlStyle',
                'verbose_name_plural': 'ControlStyles',
            },
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='PanelModel',
            fields=[
                ('uielementmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.UIElementModel')),
                ('panel_type', models.CharField(blank=True, choices=[('-1', 'Panel'), ('00', 'StackPanel'), ('01', 'FlowLayoutPanel'), ('02', 'WrapPanel'), ('03', 'DockPanel'), ('04', 'GridPanel'), ('05', 'AbsolutePanel'), ('06', 'FlyoutPanel')], default='-1', max_length=2)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(blank=True, default=None, related_name='_panelmodel_children_+', to='gui.UIElementModel')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.PanelModel')),
            ],
            options={
                'verbose_name': 'Panel',
                'verbose_name_plural': 'Panels',
            },
            bases=('gui.uielementmodel',),
        ),
        migrations.CreateModel(
            name='PlaceHolderModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('place_holder_type', models.CharField(choices=[('-1', 'None'), ('00', 'HTML'), ('01', 'Panel')], default='00', max_length=2)),
            ],
            options={
                'verbose_name': 'Placeholder',
                'verbose_name_plural': 'Placeholders',
            },
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
            bases=('gui.basemodel',),
        ),
        migrations.CreateModel(
            name='TemplateBlockModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.BaseModel')),
                ('allow_change_in_child', models.BooleanField(default=False, help_text='If checked, block can be overwritten by child templates')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sections', models.ManyToManyField(blank=True, default=None, help_text='Each block consist of 0 or more sections', related_name='_templateblockmodel_sections_+', to='gui.SectionModel')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
            },
            bases=('gui.basemodel',),
        ),
        migrations.RemoveField(
            model_name='stylemodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='stylemodel',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='stylemodel',
            name='style_applied_on',
        ),
        migrations.AlterField(
            model_name='contentcontrolmodel',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.ControlStyleModel'),
        ),
        migrations.CreateModel(
            name='HtmlPlaceHolderModel',
            fields=[
                ('placeholdermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.PlaceHolderModel')),
                ('html_tags', models.ManyToManyField(blank=True, default=None, related_name='_htmlplaceholdermodel_html_tags_+', to='gui.HtmlTag')),
            ],
            options={
                'verbose_name': 'HtmlPlaceholder',
                'verbose_name_plural': 'HtmlPlaceholders',
            },
            bases=('gui.placeholdermodel',),
        ),
        migrations.CreateModel(
            name='PanelPlaceHolderModel',
            fields=[
                ('placeholdermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.PlaceHolderModel')),
                ('panels', models.ManyToManyField(blank=True, default='None', related_name='_panelplaceholdermodel_panels_+', to='gui.PanelModel')),
            ],
            options={
                'verbose_name': 'PanelPlaceholder',
                'verbose_name_plural': 'PanelPlaceholders',
            },
            bases=('gui.placeholdermodel',),
        ),
        migrations.DeleteModel(
            name='StyleModel',
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='place_holders',
            field=models.ManyToManyField(blank=True, default=None, help_text='Each section consist of 0 or more place holders of type HTML or panel', related_name='_sectionmodel_place_holders_+', to='gui.PlaceHolderModel'),
        ),
        migrations.AddField(
            model_name='placeholdermodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='block_tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='_templatemodel_block_tags_+', to='gui.TemplateBlockModel'),
        ),
    ]
