# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0014_auto_20180117_2215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HtmlTag',
            new_name='HtmlTagModel',
        ),
        migrations.RenameModel(
            old_name='IconTag',
            new_name='IconTagModel',
        ),
        migrations.RenameModel(
            old_name='ScriptTag',
            new_name='ScriptTagModel',
        ),
        migrations.RenameModel(
            old_name='StyleTag',
            new_name='StyleTagModel',
        ),
        migrations.AlterField(
            model_name='panelplaceholdermodel',
            name='panels',
            field=models.ManyToManyField(blank=True, default=None, related_name='_panelplaceholdermodel_panels_+', to='gui.PanelModel'),
        ),
    ]
