# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gui', '0015_auto_20180117_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='htmltagmodel',
            options={'verbose_name': 'HtmlTag', 'verbose_name_plural': 'HtmlTags'},
        ),
        migrations.AlterModelOptions(
            name='icontagmodel',
            options={'verbose_name': 'IconTag', 'verbose_name_plural': 'IconTags'},
        ),
        migrations.AlterModelOptions(
            name='scripttagmodel',
            options={'verbose_name': 'ScriptTag', 'verbose_name_plural': 'ScriptTags'},
        ),
        migrations.AlterModelOptions(
            name='styletagmodel',
            options={'verbose_name': 'StyleTag', 'verbose_name_plural': 'StyleTags'},
        ),
        migrations.AddField(
            model_name='basemodel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_gui.basemodel_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='controlstylemodel',
            name='style_path',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/css', recursive=True),
        ),
        migrations.AlterField(
            model_name='icontagmodel',
            name='icon_file',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/img', recursive=True),
        ),
        migrations.AlterField(
            model_name='scripttagmodel',
            name='script_file',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/js', recursive=True),
        ),
        migrations.AlterField(
            model_name='styletagmodel',
            name='style_file',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/css', recursive=True),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='template_path',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/gui/templates', recursive=True),
        ),
    ]
