# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0017_auto_20180118_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='footer_html',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='header_html',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='controlstylemodel',
            name='style_path',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/css', recursive=True),
        ),
        migrations.AlterField(
            model_name='icontagmodel',
            name='icon_file',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/img', recursive=True),
        ),
        migrations.AlterField(
            model_name='scripttagmodel',
            name='script_file',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/js', recursive=True),
        ),
        migrations.AlterField(
            model_name='styletagmodel',
            name='style_file',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/css', recursive=True),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='template_path',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/gui/templates', recursive=True),
        ),
    ]
