# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0018_auto_20180119_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='footer_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='header_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
