# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0019_auto_20180119_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripttagmodel',
            name='position',
            field=models.CharField(choices=[('-1', 'None'), ('00', 'Header'), ('01', 'Body')], default='00', max_length=2),
        ),
    ]
