# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0020_scripttagmodel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodel',
            name='body_script_tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='_templatemodel_body_script_tags_+', to='gui.ScriptTagModel'),
        ),
    ]
