# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0021_templatemodel_body_script_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemodel',
            name='body_script_tags',
        ),
        migrations.RemoveField(
            model_name='templatemodel',
            name='header_script_tags',
        ),
        migrations.RemoveField(
            model_name='templatemodel',
            name='header_style_tags',
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='script_tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='_templatemodel_script_tags_+', to='gui.ScriptTagModel'),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='style_tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='_templatemodel_style_tags_+', to='gui.StyleTagModel'),
        ),
    ]
