# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0023_auto_20180119_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='sort_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='htmltagmodel',
            name='sort_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icontagmodel',
            name='sort_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scripttagmodel',
            name='sort_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='securityidmodel',
            name='sort_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='styletagmodel',
            name='sort_level',
            field=models.IntegerField(default=0),
        ),
    ]
