# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0024_auto_20180119_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='placeholdermodel',
            name='css_classes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placeholdermodel',
            name='tag_type',
            field=models.CharField(choices=[('-1', 'None'), ('00', 'Div'), ('00', 'Span')], default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='css_classes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='tag_type',
            field=models.CharField(choices=[('-1', 'None'), ('00', 'Div'), ('00', 'Span')], default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='templateblockmodel',
            name='css_classes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='templateblockmodel',
            name='tag_type',
            field=models.CharField(choices=[('-1', 'None'), ('00', 'Div'), ('00', 'Span')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='controlstylemodel',
            name='style_path',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/css', recursive=True),
        ),
        migrations.AlterField(
            model_name='icontagmodel',
            name='icon_file',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/img', recursive=True),
        ),
        migrations.AlterField(
            model_name='scripttagmodel',
            name='script_file',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/js', recursive=True),
        ),
        migrations.AlterField(
            model_name='styletagmodel',
            name='style_file',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/staticfiles/css', recursive=True),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='template_path',
            field=models.FilePathField(blank=True, null=True, path='/data/data/com.termux/files/home/projects/python/django/IOTStudio/IOTStudio/gui/templates', recursive=True),
        ),
    ]
