# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0026_auto_20180120_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlmodel',
            name='control_id',
            field=models.IntegerField(default=0),
        ),
    ]
