# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0027_controlmodel_control_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlmodel',
            name='control_id',
        ),
        migrations.RemoveField(
            model_name='contentcontrolmodel',
            name='content',
        ),
        migrations.AddField(
            model_name='contentcontrolmodel',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, related_name='_contentcontrolmodel_content_+', to='gui.TemplateBlockModel'),
        ),
    ]
