# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0030_auto_20180120_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateblockmodel',
            name='child_blocks',
            field=models.ManyToManyField(blank=True, default=None, related_name='_templateblockmodel_child_blocks_+', to='gui.TemplateBlockModel'),
        ),
        migrations.AlterField(
            model_name='placeholdermodel',
            name='tag_type',
            field=models.CharField(choices=[('-1', 'None'), ('00', 'Div'), ('01', 'Span')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='tag_type',
            field=models.CharField(choices=[('-1', 'None'), ('00', 'Div'), ('01', 'Span')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='templateblockmodel',
            name='tag_type',
            field=models.CharField(choices=[('-1', 'None'), ('00', 'Div'), ('01', 'Span'), ('02', 'Header'), ('03', 'Main')], default='00', max_length=2),
        ),
    ]
